@startuml
title Register
actor Pasien
participant Sistem
participant Database

Pasien -> Sistem : Isi formulir registrasi
Sistem -> Database : Cek dan simpan data akun
Database --> Sistem : Status penyimpanan

alt Data valid
    Sistem --> Pasien : Konfirmasi registrasi berhasil
else Data sudah terdaftar
    Sistem --> Pasien : Tampilkan pesan error
end
@enduml